services:
  actman:
    image: actman-image:0.0.1
    container_name: actman
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      NODE_ENV: development

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma/dev.db:/app/prisma/dev.db # Persist SQLite DB

    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - my_media_network
  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   my_network:
#     external: true
# Path: docker-compose.dev.yml
