import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import './prism.css';
import { AppProvider } from '@/providers/app';
import Navbar from '@/components/Blocks/Navbar';
import Sidebar from '@/components/Blocks/Sidebar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'ActMan',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-200`}
      >
        <AppProvider>
          <div className="drawer lg:drawer-open">
            <input id="nav-drawer" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col min-h-screen">
              <Navbar />
              <main className="p-6 container mx-auto">{children}</main>
            </div>
            <Sidebar />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}

// src/app/layout.tsx
