import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'ActMan',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex space-x-4">
            <a href="/sessions" className="text-white hover:text-gray-300">
              Sessions
            </a>
            <a href="/serviceUsers" className="text-white hover:text-gray-300">
              ServiceUsers
            </a>
            <a href="/activities" className="text-white hover:text-gray-300">
              Activities
            </a>
            <a href="/reports" className="text-white hover:text-gray-300">
              Reports
            </a>
          </div>
        </nav>
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
