name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REPOSITORY_NAME: session-management

jobs:
  build:
    # TODO: remove next line to activate the job
    if: false
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure the staging branch is checked out

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      # Build and Push Backend
      # - name: Build Backend Docker image
      #   run: |
      #     docker build --platform linux/amd64  --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:actman-app-latest -f Dockerfile.dev .
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Backend Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --no-cache \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:actman-app-latest \
            -f Dockerfile.stg .
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:actman-app-latest

# .github/workflows/ci-docker-hub.yml